[package]
name = "du"
version = "0.0.1"
authors = []

[lib]
name = "uu_du"
path = "du.rs"

[dependencies]
getopts = "*"
libc = "*"
time = "*"
uucore = { path="../uucore" }

[[bin]]
name = "du"
path = "main.rs"
