[package]
name = "uniq"
version = "0.0.1"
authors = []

[lib]
name = "uu_uniq"
path = "uniq.rs"

[dependencies]
getopts = "*"

[dependencies.uucore]
path="../uucore"
default-features = false

[[bin]]
name = "uniq"
path = "main.rs"
