[package]
name = "comm"
version = "0.0.1"
authors = []

[lib]
name = "uu_comm"
path = "comm.rs"

[dependencies]
libc = "*"
getopts = "*"
uucore = { path="../uucore" }

[[bin]]
name = "comm"
path = "main.rs"
