[package]
name = "nohup"
version = "0.0.1"
authors = []

[lib]
name = "uu_nohup"
path = "nohup.rs"

[dependencies]
getopts = "*"
libc = "*"
uucore = { path="../uucore" }

[[bin]]
name = "nohup"
path = "main.rs"
