[package]
name = "factor"
version = "0.0.1"
authors = []

[lib]
name = "uu_factor"
path = "factor.rs"

[dependencies]
libc = "*"
rand = "*"
uucore = { path="../uucore" }

[[bin]]
name = "factor"
path = "main.rs"
