[package]
name = "mktemp"
version = "0.0.1"
authors = []

[lib]
name = "uu_mktemp"
path = "mktemp.rs"

[dependencies]
uucore = { path="../uucore" }
getopts = "*"
libc = "*"
rand = "0.3"
tempfile = "*"

[[bin]]
name = "mktemp"
path = "main.rs"
