[package]
name = "tail"
version = "0.0.1"
authors = []

[lib]
name = "uu_tail"
path = "tail.rs"

[dependencies]
getopts = "*"
libc = "*"
uucore = { path="../uucore" }

[[bin]]
name = "tail"
path = "main.rs"
