[package]
name = "yes"
version = "0.0.1"
authors = []

[lib]
name = "uu_yes"
path = "yes.rs"

[dependencies]
getopts = "*"
libc = "*"
uucore = { path="../uucore" }

[[bin]]
name = "yes"
path = "main.rs"
