[package]
name = "tr"
version = "0.0.1"
authors = []

[lib]
name = "uu_tr"
path = "tr.rs"

[dependencies]
getopts = "*"
bit-set = "*"

[dependencies.uucore]
path = "../uucore"
default-features = false

[[bin]]
name = "tr"
path = "main.rs"
