[package]
name = "expand"
version = "0.0.1"
authors = []

[lib]
name = "uu_expand"
path = "expand.rs"

[dependencies]
libc = "*"
unicode-width = "*"
getopts = "*"
uucore = { path="../uucore" }

[[bin]]
name = "expand"
path = "main.rs"
