[package]
name = "touch"
version = "0.0.1"
authors = []

[lib]
name = "uu_touch"
path = "touch.rs"

[dependencies]
filetime = "*"
getopts = "*"
time = "*"

[dependencies.uucore]
path = "../uucore"
default-features = false
features = ["libc"]

[[bin]]
name = "touch"
path = "main.rs"
