[package]
name = "groups"
version = "0.0.1"
authors = []

[lib]
name = "uu_groups"
path = "groups.rs"

[dependencies]
getopts = "*"
libc = "*"
uucore = { path="../uucore" }

[[bin]]
name = "groups"
path = "main.rs"
