[package]
name = "stat"
version = "0.0.1"
authors = []

[lib]
name = "uu_stat"
path = "stat.rs"

[dependencies]
getopts = "*"
time = "*"

[dependencies.uucore]
path = "../uucore"
default-features = false
features = ["entries"]

[[bin]]
name = "stat"
path = "main.rs"
