[package]
name = "stat"
version = "0.0.1"
authors = []

[lib]
name = "uu_stat"
path = "stat.rs"

[dependencies]
getopts = "*"
libc = "^0.2"
time = "*"
uucore = { path="../uucore" }

[[bin]]
name = "stat"
path = "main.rs"
