[package]
name = "hostid"
version = "0.0.1"
authors = []

[lib]
name = "uu_hostid"
path = "hostid.rs"

[dependencies]
libc = "*"
uucore = { path="../uucore" }

[[bin]]
name = "hostid"
path = "main.rs"
