[package]
name = "pwd"
version = "0.0.1"
authors = []

[lib]
name = "uu_pwd"
path = "pwd.rs"

[dependencies]
getopts = "*"
libc = "*"
uucore = { path="../uucore" }

[[bin]]
name = "pwd"
path = "main.rs"
