[package]
name = "tee"
version = "0.0.1"
authors = []

[lib]
name = "uu_tee"
path = "tee.rs"

[dependencies]
getopts = "*"
libc = "*"
uucore = { path="../uucore" }

[[bin]]
name = "tee"
path = "main.rs"
