[package]
name = "nice"
version = "0.0.1"
authors = []

[lib]
name = "uu_nice"
path = "nice.rs"

[dependencies]
getopts = "*"
libc = "*"
uucore = { path="../uucore" }

[[bin]]
name = "nice"
path = "main.rs"
