[package]
name = "tac"
version = "0.0.1"
authors = []

[lib]
name = "uu_tac"
path = "tac.rs"

[dependencies]
getopts = "*"
libc = "*"
uucore = { path="../uucore" }

[[bin]]
name = "tac"
path = "main.rs"
