[package]
name = "head"
version = "0.0.1"
authors = []

[lib]
name = "uu_head"
path = "head.rs"

[dependencies]
getopts = "*"
libc = "*"
uucore = { path="../uucore" }

[[bin]]
name = "head"
path = "main.rs"
