[package]
name = "tty"
version = "0.0.1"
authors = []

[lib]
name = "uu_tty"
path = "tty.rs"

[dependencies]
getopts = "*"
libc = "*"
uucore = { path="../uucore" }

[[bin]]
name = "tty"
path = "main.rs"
