[package]
name = "mv"
version = "0.0.1"
authors = []

[lib]
name = "uu_mv"
path = "mv.rs"

[dependencies]
getopts = "*"

[dependencies.uucore]
path = "../uucore"
default-features = false

[[bin]]
name = "mv"
path = "main.rs"
