[package]
name = "whoami"
version = "0.0.1"
authors = []

[lib]
name = "uu_whoami"
path = "whoami.rs"

[dependencies]
getopts = "*"
winapi = "*"
advapi32-sys = "*"

[dependencies.uucore]
path = "../uucore"
default-features = false
features = ["entries"]

[[bin]]
name = "whoami"
path = "main.rs"
