[package]
name = "mkfifo"
version = "0.0.1"
authors = []

[lib]
name = "uu_mkfifo"
path = "mkfifo.rs"

[dependencies]
getopts = "*"
libc = "*"
uucore = { path="../uucore" }

[[bin]]
name = "mkfifo"
path = "main.rs"
